require('dotenv').config();
const mongoose = require('mongoose');
const Scheme = require('../models/Scheme');

async function seedSchemes() {
  await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/gramseva');
  console.log('Connected to MongoDB for scheme seeding...');

  // Delete existing schemes
  await Scheme.deleteMany({});
  console.log('Cleared existing schemes');

  const schemes = [
    // ═══ CENTRAL GOVERNMENT SCHEMES (20) ═══
    { title:'PM Kisan Samman Nidhi', titleHi:'पीएम किसान सम्मान निधि', description:'Direct income support of Rs 6000 per year to farmer families in 3 installments directly to bank accounts.', descriptionHi:'किसानों को ₹6000 सालाना DBT सहायता 3 किस्तों में सीधे बैंक खाते में।', state:'All', category:'agriculture', eligibility:'All farmer families with cultivable land', eligibilityHi:'खेती योग्य भूमि वाले सभी किसान परिवार', benefits:'Rs 6000/year', benefitsHi:'₹6000/वर्ष', applicationUrl:'https://pmkisan.gov.in', requiredDocuments:['Aadhaar Card','Land Records','Bank Account'], isActive:true },
    { title:'Ayushman Bharat PM-JAY', titleHi:'आयुष्मान भारत पीएम-जय', description:'Health insurance cover of Rs 5 lakh per family per year for secondary and tertiary care hospitalization.', descriptionHi:'₹5 लाख तक का हेल्थ इंश्योरेंस प्रति परिवार प्रति वर्ष।', state:'All', category:'health', eligibility:'BPL families as per SECC data', eligibilityHi:'SECC डेटा के अनुसार BPL परिवार', benefits:'Rs 5 lakh health cover', benefitsHi:'₹5 लाख स्वास्थ्य कवर', applicationUrl:'https://pmjay.gov.in', requiredDocuments:['Aadhaar Card','Ration Card','Income Certificate'], isActive:true },
    { title:'PM Awas Yojana (Gramin)', titleHi:'पीएम आवास योजना (ग्रामीण)', description:'Financial assistance for construction of pucca house for rural poor families.', descriptionHi:'ग्रामीण गरीब परिवारों को पक्का घर बनाने हेतु आर्थिक सहायता।', state:'All', category:'housing', eligibility:'Houseless or living in kutcha house', eligibilityHi:'बेघर या कच्चे घर में रहने वाले', benefits:'Rs 1.2 lakh (plains), Rs 1.3 lakh (hilly)', benefitsHi:'₹1.2 लाख (मैदानी), ₹1.3 लाख (पहाड़ी)', applicationUrl:'https://pmayg.nic.in', requiredDocuments:['Aadhaar Card','BPL Certificate','Land Documents'], isActive:true },
    { title:'PM Ujjwala Yojana', titleHi:'पीएम उज्ज्वला योजना', description:'Free LPG gas connection to women from BPL households.', descriptionHi:'BPL परिवारों की महिलाओं को फ्री LPG गैस कनेक्शन।', state:'All', category:'women', eligibility:'Women from BPL households', eligibilityHi:'BPL परिवारों की महिलाएं', benefits:'Free LPG connection + first refill', benefitsHi:'फ्री LPG कनेक्शन + पहला रिफिल', applicationUrl:'https://www.pmuy.gov.in', requiredDocuments:['Aadhaar Card','BPL Card','Bank Account'], isActive:true },
    { title:'PM Mudra Yojana', titleHi:'पीएम मुद्रा योजना', description:'Collateral-free business loans up to Rs 10 lakh for micro enterprises.', descriptionHi:'बिना collateral ₹10 लाख तक का बिजनेस लोन।', state:'All', category:'finance', eligibility:'Any Indian citizen with business plan', eligibilityHi:'बिजनेस प्लान वाला कोई भी भारतीय नागरिक', benefits:'Loan up to Rs 10 lakh', benefitsHi:'₹10 लाख तक लोन', applicationUrl:'https://www.mudra.org.in', requiredDocuments:['Aadhaar Card','Business Plan','Bank Account'], isActive:true },
    { title:'PM Vishwakarma Yojana', titleHi:'पीएम विश्वकर्मा योजना', description:'Training and loan support for traditional artisans and craftspeople.', descriptionHi:'कारीगरों और artisans के लिए training + loan सहायता।', state:'All', category:'finance', eligibility:'Traditional artisans and craftspeople', eligibilityHi:'पारंपरिक कारीगर और शिल्पकार', benefits:'Training + Rs 3 lakh loan at 5%', benefitsHi:'ट्रेनिंग + ₹3 लाख लोन 5% पर', applicationUrl:'https://pmvishwakarma.gov.in', requiredDocuments:['Aadhaar Card','Skill Certificate','Bank Account'], isActive:true },
    { title:'PM Fasal Bima Yojana', titleHi:'पीएम फसल बीमा योजना', description:'Crop insurance scheme protecting farmers against crop loss due to natural calamities.', descriptionHi:'प्राकृतिक आपदाओं से फसल नुकसान के खिलाफ किसानों की सुरक्षा।', state:'All', category:'agriculture', eligibility:'All farmers growing notified crops', eligibilityHi:'अधिसूचित फसल उगाने वाले सभी किसान', benefits:'Crop insurance at low premium', benefitsHi:'कम प्रीमियम पर फसल बीमा', applicationUrl:'https://pmfby.gov.in', requiredDocuments:['Aadhaar Card','Land Records','Bank Account','Sowing Certificate'], isActive:true },
    { title:'e-Shram Card', titleHi:'ई-श्रम कार्ड', description:'Registration portal for unorganized sector workers with Rs 2 lakh accidental insurance.', descriptionHi:'असंगठित क्षेत्र के मजदूरों का registration + ₹2 लाख दुर्घटना बीमा।', state:'All', category:'finance', eligibility:'Unorganized sector workers aged 16-59', eligibilityHi:'16-59 वर्ष के असंगठित मजदूर', benefits:'Rs 2 lakh insurance + govt benefits', benefitsHi:'₹2 लाख बीमा + सरकारी लाभ', applicationUrl:'https://eshram.gov.in', requiredDocuments:['Aadhaar Card','Mobile Number','Bank Account'], isActive:true },
    { title:'Atal Pension Yojana', titleHi:'अटल पेंशन योजना', description:'Guaranteed pension of Rs 1000-5000 per month after age 60 for unorganized workers.', descriptionHi:'60 वर्ष बाद ₹1000-5000 मासिक pension गारंटी।', state:'All', category:'finance', eligibility:'Indian citizens aged 18-40 with bank account', eligibilityHi:'18-40 वर्ष के बैंक खाता धारक', benefits:'Rs 1000-5000/month pension', benefitsHi:'₹1000-5000/माह पेंशन', applicationUrl:'https://www.npscra.nsdl.co.in/scheme-details.php', requiredDocuments:['Aadhaar Card','Bank Account','Mobile Number'], isActive:true },
    { title:'PM Jeevan Jyoti Bima', titleHi:'पीएम जीवन ज्योति बीमा', description:'Life insurance of Rs 2 lakh at just Rs 436 per year premium.', descriptionHi:'मात्र ₹436/वर्ष में ₹2 लाख का जीवन बीमा।', state:'All', category:'health', eligibility:'Age 18-50 with bank account', eligibilityHi:'18-50 वर्ष बैंक खाता धारक', benefits:'Rs 2 lakh life cover', benefitsHi:'₹2 लाख जीवन बीमा', applicationUrl:'https://www.jansuraksha.gov.in', requiredDocuments:['Aadhaar Card','Bank Account'], isActive:true },
    { title:'PM Suraksha Bima Yojana', titleHi:'पीएम सुरक्षा बीमा योजना', description:'Accidental insurance of Rs 2 lakh at just Rs 20 per year.', descriptionHi:'मात्र ₹20/वर्ष में ₹2 लाख दुर्घटना बीमा।', state:'All', category:'health', eligibility:'Age 18-70 with bank account', eligibilityHi:'18-70 वर्ष बैंक खाता धारक', benefits:'Rs 2 lakh accident cover', benefitsHi:'₹2 लाख दुर्घटना कवर', applicationUrl:'https://www.jansuraksha.gov.in', requiredDocuments:['Aadhaar Card','Bank Account'], isActive:true },
    { title:'Sukanya Samriddhi Yojana', titleHi:'सुकन्या समृद्धि योजना', description:'Savings scheme for girl child with high interest rate and tax benefits.', descriptionHi:'बेटियों के लिए उच्च ब्याज दर वाली बचत योजना।', state:'All', category:'women', eligibility:'Parents of girl child below 10 years', eligibilityHi:'10 वर्ष से कम उम्र की बेटी के माता-पिता', benefits:'8.2% interest + tax free', benefitsHi:'8.2% ब्याज + कर मुक्त', applicationUrl:'https://www.nsiindia.gov.in', requiredDocuments:['Birth Certificate','Aadhaar Card','Parent ID'], isActive:true },
    { title:'Stand Up India', titleHi:'स्टैंड अप इंडिया', description:'Loans between Rs 10 lakh to Rs 1 crore for SC/ST and women entrepreneurs.', descriptionHi:'SC/ST और महिला उद्यमियों को ₹10 लाख से ₹1 करोड़ तक लोन।', state:'All', category:'finance', eligibility:'SC/ST or women entrepreneurs above 18', eligibilityHi:'18+ SC/ST या महिला उद्यमी', benefits:'Rs 10 lakh to 1 crore loan', benefitsHi:'₹10 लाख से ₹1 करोड़ लोन', applicationUrl:'https://www.standupmitra.in', requiredDocuments:['Aadhaar Card','Caste Certificate','Business Plan'], isActive:true },
    { title:'Skill India Mission', titleHi:'स्किल इंडिया मिशन', description:'Free skill development training for youth in various trades.', descriptionHi:'युवाओं के लिए विभिन्न ट्रेड में मुफ्त कौशल विकास प्रशिक्षण।', state:'All', category:'education', eligibility:'Indian youth aged 15-45', eligibilityHi:'15-45 वर्ष के भारतीय युवा', benefits:'Free training + certificate', benefitsHi:'मुफ्त प्रशिक्षण + प्रमाणपत्र', applicationUrl:'https://www.skillindia.gov.in', requiredDocuments:['Aadhaar Card','Education Certificate'], isActive:true },
    { title:'Jan Dhan Yojana', titleHi:'जन धन योजना', description:'Zero balance bank account with RuPay debit card and Rs 2 lakh accident cover.', descriptionHi:'जीरो बैलेंस बैंक खाता + RuPay कार्ड + ₹2 लाख दुर्घटना बीमा।', state:'All', category:'finance', eligibility:'Any Indian citizen without bank account', eligibilityHi:'बिना बैंक खाते वाला कोई भी भारतीय', benefits:'Zero balance account + insurance', benefitsHi:'जीरो बैलेंस खाता + बीमा', applicationUrl:'https://pmjdy.gov.in', requiredDocuments:['Aadhaar Card','Address Proof'], isActive:true },
    { title:'PM SVANidhi', titleHi:'पीएम स्वनिधि', description:'Micro credit facility for street vendors - loan up to Rs 50,000.', descriptionHi:'स्ट्रीट वेंडर्स को ₹50,000 तक का माइक्रो क्रेडिट।', state:'All', category:'finance', eligibility:'Street vendors with vending certificate', eligibilityHi:'वेंडिंग सर्टिफिकेट वाले स्ट्रीट वेंडर', benefits:'Rs 10K-50K loan at low interest', benefitsHi:'₹10K-50K कम ब्याज पर लोन', applicationUrl:'https://pmsvanidhi.mohua.gov.in', requiredDocuments:['Aadhaar Card','Vending Certificate','Bank Account'], isActive:true },
    { title:'One Nation One Ration Card', titleHi:'वन नेशन वन राशन कार्ड', description:'Get ration from any fair price shop across India using same ration card.', descriptionHi:'एक ही राशन कार्ड से पूरे भारत में कहीं भी राशन लें।', state:'All', category:'other', eligibility:'All ration card holders', eligibilityHi:'सभी राशन कार्ड धारक', benefits:'Portable ration facility', benefitsHi:'पोर्टेबल राशन सुविधा', applicationUrl:'https://nfsa.gov.in/portal/onorc', requiredDocuments:['Ration Card','Aadhaar Card'], isActive:true },
    { title:'National Apprenticeship Scheme', titleHi:'राष्ट्रीय अप्रेंटिसशिप योजना', description:'Apprenticeship and internship opportunities with stipend for youth.', descriptionHi:'युवाओं के लिए stipend के साथ apprenticeship अवसर।', state:'All', category:'education', eligibility:'Youth aged 14+ with minimum 5th pass', eligibilityHi:'14+ वर्ष, न्यूनतम 5वीं पास', benefits:'Stipend + training + certificate', benefitsHi:'स्टाइपेंड + ट्रेनिंग + सर्टिफिकेट', applicationUrl:'https://www.apprenticeshipindia.gov.in', requiredDocuments:['Aadhaar Card','Education Certificate'], isActive:true },
    { title:'Digital India Mission', titleHi:'डिजिटल इंडिया मिशन', description:'Digital services, certificates, and government services online.', descriptionHi:'डिजिटल सेवाएं, प्रमाणपत्र और सरकारी सेवाएं ऑनलाइन।', state:'All', category:'other', eligibility:'All Indian citizens', eligibilityHi:'सभी भारतीय नागरिक', benefits:'Online govt services', benefitsHi:'ऑनलाइन सरकारी सेवाएं', applicationUrl:'https://www.digitalindia.gov.in', requiredDocuments:['Aadhaar Card','Mobile Number'], isActive:true },
    { title:'MGNREGA - 100 Days Employment', titleHi:'मनरेगा - 100 दिन रोजगार', description:'Guaranteed 100 days wage employment per year for rural households.', descriptionHi:'ग्रामीण परिवारों को 100 दिन रोजगार गारंटी। ₹247/दिन मजदूरी।', state:'All', category:'agriculture', eligibility:'Rural household members willing to do manual work', eligibilityHi:'ग्रामीण परिवार के सदस्य जो शारीरिक काम करने को तैयार', benefits:'Rs 247/day for 100 days', benefitsHi:'₹247/दिन, 100 दिन', applicationUrl:'https://nrega.nic.in', requiredDocuments:['Job Card','Aadhaar Card','Bank Account'], isActive:true },

    // ═══ BIHAR SCHEMES (8) ═══
    { title:'Mukhyamantri Kanya Utthan Yojana', titleHi:'मुख्यमंत्री कन्या उत्थान योजना', description:'Financial support for girls from birth to graduation - total Rs 50,000.', descriptionHi:'लड़कियों को जन्म से स्नातक तक ₹50,000 की आर्थिक सहायता।', state:'Bihar', category:'women', eligibility:'All girls born in Bihar', eligibilityHi:'बिहार में जन्मी सभी लड़कियां', benefits:'Rs 50,000 total', benefitsHi:'₹50,000 कुल', applicationUrl:'https://edudbt.bih.nic.in', requiredDocuments:['Birth Certificate','Aadhaar Card','Bank Account'], isActive:true },
    { title:'Bihar Student Credit Card', titleHi:'बिहार स्टूडेंट क्रेडिट कार्ड', description:'Education loan up to Rs 4 lakh for higher education. 0% interest for girls.', descriptionHi:'उच्च शिक्षा के लिए ₹4 लाख तक लोन। लड़कियों के लिए 0% ब्याज।', state:'Bihar', category:'education', eligibility:'Bihar domicile students for higher education', eligibilityHi:'बिहार के छात्र जो उच्च शिक्षा चाहते हैं', benefits:'Rs 4 lakh loan', benefitsHi:'₹4 लाख लोन', applicationUrl:'https://www.7nishchay-yuvaupmission.bihar.gov.in', requiredDocuments:['12th Marksheet','Aadhaar Card','Admission Letter'], isActive:true },
    { title:'Mukhyamantri Vridhjan Pension', titleHi:'मुख्यमंत्री वृद्धजन पेंशन योजना', description:'Monthly pension of Rs 400-500 for senior citizens above 60 years.', descriptionHi:'60 वर्ष से अधिक बुजुर्गों को ₹400-500 मासिक पेंशन।', state:'Bihar', category:'other', eligibility:'Bihar residents above 60 years', eligibilityHi:'60+ वर्ष के बिहार निवासी', benefits:'Rs 400-500/month', benefitsHi:'₹400-500/माह', applicationUrl:'https://www.serviceonline.bihar.gov.in', requiredDocuments:['Aadhaar Card','Age Proof','Bank Account'], isActive:true },
    { title:'Bihar Berojgari Bhatta', titleHi:'बिहार बेरोजगारी भत्ता', description:'Unemployment allowance of Rs 1000/month for educated unemployed youth.', descriptionHi:'शिक्षित बेरोजगार युवाओं को ₹1000/माह भत्ता।', state:'Bihar', category:'education', eligibility:'12th pass unemployed youth of Bihar', eligibilityHi:'12वीं पास बिहार के बेरोजगार युवा', benefits:'Rs 1000/month', benefitsHi:'₹1000/माह', applicationUrl:'https://www.7nishchay-yuvaupmission.bihar.gov.in', requiredDocuments:['12th Certificate','Aadhaar Card','Domicile'], isActive:true },
    { title:'Mukhyamantri Kanya Vivah Yojana', titleHi:'मुख्यमंत्री कन्या विवाह योजना', description:'Rs 5000 financial assistance for marriage of girls from BPL families.', descriptionHi:'BPL परिवारों की लड़कियों की शादी के लिए ₹5000 सहायता।', state:'Bihar', category:'women', eligibility:'BPL family girls above 18 years', eligibilityHi:'18+ वर्ष BPL परिवार की लड़कियां', benefits:'Rs 5000', benefitsHi:'₹5000', applicationUrl:'https://www.serviceonline.bihar.gov.in', requiredDocuments:['Aadhaar Card','BPL Card','Age Proof'], isActive:true },
    { title:'Har Ghar Nal Ka Jal', titleHi:'हर घर नल का जल योजना', description:'Piped drinking water supply to every rural household in Bihar.', descriptionHi:'बिहार के हर ग्रामीण घर में पाइप से पीने का पानी।', state:'Bihar', category:'other', eligibility:'All rural households in Bihar', eligibilityHi:'बिहार के सभी ग्रामीण परिवार', benefits:'Free piped water', benefitsHi:'मुफ्त पाइप जल', applicationUrl:'https://phed.bihar.gov.in', requiredDocuments:['Aadhaar Card','Address Proof'], isActive:true },
    { title:'Bihar Krishi Input Anudan', titleHi:'बिहार कृषि इनपुट अनुदान', description:'Financial assistance to farmers affected by natural calamities - up to Rs 13500/hectare.', descriptionHi:'प्राकृतिक आपदा से प्रभावित किसानों को ₹13500/हेक्टेयर तक सहायता।', state:'Bihar', category:'agriculture', eligibility:'Farmers affected by flood/drought in Bihar', eligibilityHi:'बाढ़/सूखे से प्रभावित बिहार के किसान', benefits:'Up to Rs 13500/hectare', benefitsHi:'₹13500/हेक्टेयर तक', applicationUrl:'https://dbtagriculture.bihar.gov.in', requiredDocuments:['Aadhaar Card','Land Records','Damage Report'], isActive:true },
    { title:'Mukhyamantri Udyami Yojana', titleHi:'मुख्यमंत्री उद्यमी योजना', description:'Rs 10 lakh loan at subsidized rate for new businesses by SC/ST/OBC/Women.', descriptionHi:'SC/ST/OBC/महिलाओं को नए बिजनेस के लिए ₹10 लाख लोन।', state:'Bihar', category:'finance', eligibility:'SC/ST/OBC/Women of Bihar aged 18-50', eligibilityHi:'18-50 वर्ष बिहार के SC/ST/OBC/महिला', benefits:'Rs 10 lakh loan + 50% subsidy', benefitsHi:'₹10 लाख लोन + 50% सब्सिडी', applicationUrl:'https://udyami.bihar.gov.in', requiredDocuments:['Aadhaar Card','Caste Certificate','Business Plan'], isActive:true },

    // ═══ UTTAR PRADESH SCHEMES (8) ═══
    { title:'Kanya Sumangala Yojana', titleHi:'कन्या सुमंगला योजना', description:'Rs 15,000 financial support for girls in 6 stages from birth to graduation.', descriptionHi:'बेटियों को जन्म से स्नातक तक 6 चरणों में ₹15,000 सहायता।', state:'Uttar Pradesh', category:'women', eligibility:'UP families with annual income below Rs 3 lakh', eligibilityHi:'₹3 लाख से कम आय वाले UP परिवार', benefits:'Rs 15,000 in 6 stages', benefitsHi:'₹15,000 (6 चरणों में)', applicationUrl:'https://mksy.up.gov.in', requiredDocuments:['Birth Certificate','Aadhaar Card','Income Certificate'], isActive:true },
    { title:'UP Free Tablet/Smartphone Scheme', titleHi:'यूपी फ्री टैबलेट/स्मार्टफोन योजना', description:'Free tablets and smartphones for students scoring 65%+ marks.', descriptionHi:'65%+ अंक लाने वाले छात्रों को फ्री टैबलेट/स्मार्टफोन।', state:'Uttar Pradesh', category:'education', eligibility:'UP students scoring 65%+ in board exams', eligibilityHi:'बोर्ड में 65%+ अंक वाले UP छात्र', benefits:'Free Tablet/Smartphone', benefitsHi:'फ्री टैबलेट/स्मार्टफोन', applicationUrl:'https://digishakti.up.gov.in', requiredDocuments:['Marksheet','Aadhaar Card','College ID'], isActive:true },
    { title:'Mukhyamantri Samuhik Vivah Yojana', titleHi:'मुख्यमंत्री सामूहिक विवाह योजना', description:'Rs 51,000 assistance for marriage of girls from poor families.', descriptionHi:'गरीब परिवारों की लड़कियों की शादी के लिए ₹51,000 सहायता।', state:'Uttar Pradesh', category:'women', eligibility:'BPL families in UP', eligibilityHi:'UP के BPL परिवार', benefits:'Rs 51,000', benefitsHi:'₹51,000', applicationUrl:'https://sspy-up.gov.in', requiredDocuments:['Aadhaar Card','Income Certificate','Age Proof'], isActive:true },
    { title:'Nirashrit Mahila Pension', titleHi:'निराश्रित महिला पेंशन', description:'Monthly pension for destitute/widow women in UP.', descriptionHi:'UP की निराश्रित/विधवा महिलाओं को मासिक पेंशन।', state:'Uttar Pradesh', category:'women', eligibility:'Widow/destitute women in UP', eligibilityHi:'UP की विधवा/निराश्रित महिलाएं', benefits:'Rs 500/month', benefitsHi:'₹500/माह', applicationUrl:'https://sspy-up.gov.in', requiredDocuments:['Aadhaar Card','Death Certificate of Husband','Bank Account'], isActive:true },
    { title:'Mukhyamantri Yuva Swarozgar Yojana', titleHi:'मुख्यमंत्री युवा स्वरोजगार योजना', description:'Loan support up to Rs 25 lakh for self-employment of youth.', descriptionHi:'युवाओं के स्वरोजगार के लिए ₹25 लाख तक लोन सहायता।', state:'Uttar Pradesh', category:'finance', eligibility:'UP youth aged 18-40', eligibilityHi:'18-40 वर्ष UP के युवा', benefits:'Rs 25 lakh loan', benefitsHi:'₹25 लाख लोन', applicationUrl:'https://diupmsme.upsdc.gov.in', requiredDocuments:['Aadhaar Card','Education Certificate','Business Plan'], isActive:true },
    { title:'UP Scholarship Scheme', titleHi:'यूपी छात्रवृत्ति योजना', description:'Scholarship for SC/ST/OBC/Minority students from class 9 to post-graduation.', descriptionHi:'कक्षा 9 से PG तक SC/ST/OBC/अल्पसंख्यक छात्रों को छात्रवृत्ति।', state:'Uttar Pradesh', category:'education', eligibility:'SC/ST/OBC/Minority students in UP', eligibilityHi:'UP के SC/ST/OBC/अल्पसंख्यक छात्र', benefits:'Tuition fee + maintenance', benefitsHi:'ट्यूशन फीस + मेंटेनेंस', applicationUrl:'https://scholarship.up.gov.in', requiredDocuments:['Marksheet','Caste Certificate','Income Certificate','Aadhaar'], isActive:true },
    { title:'Kisan Evam Sarvhit Bima Yojana', titleHi:'किसान एवं सर्वहित बीमा योजना', description:'Insurance coverage for farmers and BPL families in UP.', descriptionHi:'UP के किसानों और BPL परिवारों के लिए बीमा कवरेज।', state:'Uttar Pradesh', category:'agriculture', eligibility:'Farmers and BPL families in UP', eligibilityHi:'UP के किसान और BPL परिवार', benefits:'Rs 5 lakh insurance', benefitsHi:'₹5 लाख बीमा', applicationUrl:'https://balrampur.nic.in', requiredDocuments:['Aadhaar Card','Land Records','BPL Card'], isActive:true },
    { title:'BC Sakhi Scheme (UP)', titleHi:'बीसी सखी योजना (यूपी)', description:'Women as Bank Correspondents in villages with Rs 4000/month stipend.', descriptionHi:'गांवों में महिलाओं को बैंक सखी बनाकर ₹4000/माह स्टाइपेंड।', state:'Uttar Pradesh', category:'women', eligibility:'Women in UP villages with 10th pass', eligibilityHi:'10वीं पास UP ग्रामीण महिलाएं', benefits:'Rs 4000/month + commission', benefitsHi:'₹4000/माह + कमीशन', applicationUrl:'https://up.gov.in', requiredDocuments:['Aadhaar Card','10th Certificate','Bank Account'], isActive:true },

    // ═══ PUNJAB SCHEMES (8) ═══
    { title:'Punjab Ashirwad Scheme', titleHi:'पंजाब आशीर्वाद योजना', description:'Rs 21,000 financial assistance for marriage of SC girls.', descriptionHi:'SC लड़कियों की शादी के लिए ₹21,000 आर्थिक सहायता।', state:'Punjab', category:'women', eligibility:'SC families in Punjab', eligibilityHi:'पंजाब के SC परिवार', benefits:'Rs 21,000', benefitsHi:'₹21,000', applicationUrl:'https://punjab.gov.in', requiredDocuments:['Aadhaar Card','Caste Certificate','Marriage Card'], isActive:true },
    { title:'Ghar Ghar Rozgar', titleHi:'घर घर रोजगार', description:'Employment portal connecting job seekers with employers in Punjab.', descriptionHi:'पंजाब में नौकरी चाहने वालों को employers से जोड़ने वाला पोर्टल।', state:'Punjab', category:'education', eligibility:'Punjab residents seeking employment', eligibilityHi:'रोजगार चाहने वाले पंजाब निवासी', benefits:'Job placement support', benefitsHi:'नौकरी प्लेसमेंट सहायता', applicationUrl:'https://www.pgrkam.com', requiredDocuments:['Aadhaar Card','Resume','Education Certificates'], isActive:true },
    { title:'Sarbat Sehat Bima Yojana', titleHi:'सरबत सेहत बीमा योजना', description:'Health insurance of Rs 5 lakh for all families in Punjab.', descriptionHi:'पंजाब के सभी परिवारों को ₹5 लाख स्वास्थ्य बीमा।', state:'Punjab', category:'health', eligibility:'All families in Punjab', eligibilityHi:'पंजाब के सभी परिवार', benefits:'Rs 5 lakh health cover', benefitsHi:'₹5 लाख स्वास्थ्य कवर', applicationUrl:'https://sha.punjab.gov.in', requiredDocuments:['Aadhaar Card','Ration Card'], isActive:true },
    { title:'Punjab Scholarship Scheme', titleHi:'पंजाब छात्रवृत्ति योजना', description:'Scholarship for SC/BC students in Punjab for higher education.', descriptionHi:'पंजाब के SC/BC छात्रों को उच्च शिक्षा के लिए छात्रवृत्ति।', state:'Punjab', category:'education', eligibility:'SC/BC students in Punjab', eligibilityHi:'पंजाब के SC/BC छात्र', benefits:'Full tuition fee', benefitsHi:'पूरी ट्यूशन फीस', applicationUrl:'https://punjabscholarships.gov.in', requiredDocuments:['Marksheet','Caste Certificate','Income Certificate'], isActive:true },
    { title:'Punjab Shagun Scheme', titleHi:'पंजाब शगुन योजना', description:'Marriage assistance for daughters of BPL/SC families.', descriptionHi:'BPL/SC परिवारों की बेटियों की शादी सहायता।', state:'Punjab', category:'women', eligibility:'BPL/SC families in Punjab', eligibilityHi:'पंजाब के BPL/SC परिवार', benefits:'Rs 21,000-51,000', benefitsHi:'₹21,000-51,000', applicationUrl:'https://punjab.gov.in', requiredDocuments:['Aadhaar Card','BPL Card','Marriage Certificate'], isActive:true },
    { title:'Kisan Karj Rahat Yojana Punjab', titleHi:'किसान कर्ज राहत योजना पंजाब', description:'Farm loan waiver scheme for small and marginal farmers.', descriptionHi:'छोटे और सीमांत किसानों के लिए कर्ज माफी योजना।', state:'Punjab', category:'agriculture', eligibility:'Small/marginal farmers in Punjab with loans', eligibilityHi:'कर्ज वाले पंजाब के छोटे/सीमांत किसान', benefits:'Loan waiver up to Rs 2 lakh', benefitsHi:'₹2 लाख तक कर्ज माफी', applicationUrl:'https://agri.punjab.gov.in', requiredDocuments:['Aadhaar Card','Land Records','Loan Documents'], isActive:true },
    { title:'Punjab Old Age Pension', titleHi:'पंजाब वृद्धावस्था पेंशन', description:'Monthly pension for senior citizens above 65 years.', descriptionHi:'65 वर्ष से अधिक बुजुर्गों को मासिक पेंशन।', state:'Punjab', category:'other', eligibility:'Punjab residents above 65 years', eligibilityHi:'65+ वर्ष पंजाब निवासी', benefits:'Rs 1500/month', benefitsHi:'₹1500/माह', applicationUrl:'https://punjab.gov.in', requiredDocuments:['Aadhaar Card','Age Proof','Bank Account'], isActive:true },
    { title:'Punjab Smart Ration Card', titleHi:'पंजाब स्मार्ट राशन कार्ड', description:'Digital ration card for subsidized food grains.', descriptionHi:'सब्सिडी वाले अनाज के लिए डिजिटल राशन कार्ड।', state:'Punjab', category:'other', eligibility:'All eligible families in Punjab', eligibilityHi:'पंजाब के सभी पात्र परिवार', benefits:'Subsidized ration', benefitsHi:'सब्सिडी वाला राशन', applicationUrl:'https://epos.punjab.gov.in', requiredDocuments:['Aadhaar Card','Address Proof','Income Certificate'], isActive:true },
    // ═══ HARYANA SCHEMES (8) ═══
    { title:'Chirayu Ayushman Haryana', titleHi:'चिरायु आयुष्मान हरियाणा', description:'Health insurance extension - Rs 5 lakh cover for families with income up to Rs 1.8 lakh.', descriptionHi:'₹1.8 लाख तक आय वाले परिवारों को ₹5 लाख स्वास्थ्य बीमा।', state:'Haryana', category:'health', eligibility:'Haryana families with income up to Rs 1.8 lakh', eligibilityHi:'₹1.8 लाख तक आय वाले हरियाणा परिवार', benefits:'Rs 5 lakh health cover', benefitsHi:'₹5 लाख स्वास्थ्य कवर', applicationUrl:'https://chirayuayushmanharyana.in', requiredDocuments:['Parivar Pehchan Patra','Aadhaar Card'], isActive:true },
    { title:'Parivar Pehchan Patra', titleHi:'परिवार पहचान पत्र', description:'Unique family ID for all government services and benefits in Haryana.', descriptionHi:'हरियाणा में सभी सरकारी सेवाओं के लिए यूनिक फैमिली ID।', state:'Haryana', category:'other', eligibility:'All families in Haryana', eligibilityHi:'हरियाणा के सभी परिवार', benefits:'Access to all govt schemes', benefitsHi:'सभी सरकारी योजनाओं तक पहुंच', applicationUrl:'https://meraparivar.haryana.gov.in', requiredDocuments:['Aadhaar Card','Address Proof','Family Details'], isActive:true },
    { title:'Old Age Samman Allowance', titleHi:'वृद्धावस्था सम्मान भत्ता', description:'Monthly pension of Rs 2500 for senior citizens above 60 years.', descriptionHi:'60 वर्ष से अधिक बुजुर्गों को ₹2500 मासिक पेंशन।', state:'Haryana', category:'other', eligibility:'Haryana residents above 60 years', eligibilityHi:'60+ वर्ष हरियाणा निवासी', benefits:'Rs 2500/month', benefitsHi:'₹2500/माह', applicationUrl:'https://saralharyana.gov.in', requiredDocuments:['Aadhaar Card','PPP ID','Bank Account'], isActive:true },
    { title:'Haryana Kaushal Rozgar Nigam', titleHi:'हरियाणा कौशल रोजगार निगम', description:'Employment portal for contractual hiring in government departments.', descriptionHi:'सरकारी विभागों में ठेका भर्ती के लिए रोजगार पोर्टल।', state:'Haryana', category:'education', eligibility:'Haryana domicile youth', eligibilityHi:'हरियाणा अधिवास युवा', benefits:'Government contractual jobs', benefitsHi:'सरकारी ठेका नौकरियां', applicationUrl:'https://hkrnl.itiharyana.gov.in', requiredDocuments:['Aadhaar Card','Domicile','Education Certificates'], isActive:true },
    { title:'Ladli Scheme Haryana', titleHi:'लाडली योजना हरियाणा', description:'Rs 5000 per year for second girl child until she turns 18.', descriptionHi:'दूसरी बेटी के लिए 18 वर्ष तक ₹5000/वर्ष।', state:'Haryana', category:'women', eligibility:'Families with second girl child in Haryana', eligibilityHi:'हरियाणा में दूसरी बेटी वाले परिवार', benefits:'Rs 5000/year till 18', benefitsHi:'₹5000/वर्ष 18 तक', applicationUrl:'https://wcdhry.gov.in', requiredDocuments:['Birth Certificate','Aadhaar Card','Bank Account'], isActive:true },
    { title:'Mukhyamantri Vivah Shagun', titleHi:'मुख्यमंत्री विवाह शगुन', description:'Marriage assistance of Rs 11,000-51,000 for BPL/SC/widow families.', descriptionHi:'BPL/SC/विधवा परिवारों को शादी सहायता ₹11,000-51,000।', state:'Haryana', category:'women', eligibility:'BPL/SC/Widow families in Haryana', eligibilityHi:'हरियाणा के BPL/SC/विधवा परिवार', benefits:'Rs 11,000-51,000', benefitsHi:'₹11,000-51,000', applicationUrl:'https://saralharyana.gov.in', requiredDocuments:['Aadhaar Card','BPL/Caste Certificate','Marriage Card'], isActive:true },
    { title:'Saksham Yuva Yojana', titleHi:'सक्षम युवा योजना', description:'Unemployment allowance + honorarium for educated unemployed youth.', descriptionHi:'शिक्षित बेरोजगार युवाओं को बेरोजगारी भत्ता + मानदेय।', state:'Haryana', category:'education', eligibility:'Graduate/Post-graduate unemployed youth of Haryana', eligibilityHi:'हरियाणा के स्नातक/स्नातकोत्तर बेरोजगार युवा', benefits:'Rs 3000-9000/month', benefitsHi:'₹3000-9000/माह', applicationUrl:'https://hreyahs.gov.in', requiredDocuments:['Degree Certificate','Aadhaar Card','Domicile'], isActive:true },
    { title:'Haryana Solar Water Pumping', titleHi:'हरियाणा सोलर वॉटर पंपिंग', description:'Subsidy on solar water pumps for farmers for irrigation.', descriptionHi:'किसानों को सिंचाई के लिए सोलर पंप पर सब्सिडी।', state:'Haryana', category:'agriculture', eligibility:'Farmers in Haryana with agricultural land', eligibilityHi:'कृषि भूमि वाले हरियाणा के किसान', benefits:'75% subsidy on solar pump', benefitsHi:'सोलर पंप पर 75% सब्सिडी', applicationUrl:'https://hareda.gov.in', requiredDocuments:['Aadhaar Card','Land Records','Bank Account'], isActive:true },

    // ═══ JHARKHAND SCHEMES (8) ═══
    { title:'Savitribai Phule Kishori Samridhi', titleHi:'सावित्रीबाई फुले किशोरी समृद्धि', description:'Financial support for girls from class 8 to 12 - Rs 40,000 total.', descriptionHi:'कक्षा 8 से 12 तक लड़कियों को ₹40,000 तक आर्थिक सहायता।', state:'Jharkhand', category:'women', eligibility:'Girls studying in class 8-12 in Jharkhand', eligibilityHi:'झारखंड में कक्षा 8-12 में पढ़ने वाली लड़कियां', benefits:'Rs 40,000 total', benefitsHi:'₹40,000 कुल', applicationUrl:'https://jharkhand.gov.in', requiredDocuments:['School Certificate','Aadhaar Card','Bank Account'], isActive:true },
    { title:'Jharkhand Ration Card', titleHi:'झारखंड राशन कार्ड', description:'Food security scheme providing subsidized grains to eligible families.', descriptionHi:'पात्र परिवारों को सब्सिडी वाला अनाज।', state:'Jharkhand', category:'other', eligibility:'BPL families in Jharkhand', eligibilityHi:'झारखंड के BPL परिवार', benefits:'Subsidized food grains', benefitsHi:'सब्सिडी वाला अनाज', applicationUrl:'https://aahar.jharkhand.gov.in', requiredDocuments:['Aadhaar Card','Income Certificate','Address Proof'], isActive:true },
    { title:'Birsa Harit Gram Yojana', titleHi:'बिरसा हरित ग्राम योजना', description:'Plantation drive providing employment + fruit trees to rural families.', descriptionHi:'ग्रामीण परिवारों को रोजगार + फलदार पेड़ लगाने की योजना।', state:'Jharkhand', category:'agriculture', eligibility:'Rural families in Jharkhand', eligibilityHi:'झारखंड के ग्रामीण परिवार', benefits:'Employment + fruit trees', benefitsHi:'रोजगार + फलदार पेड़', applicationUrl:'https://jrda.jharkhand.gov.in', requiredDocuments:['Aadhaar Card','Land Records'], isActive:true },
    { title:'Guruji Student Credit Card', titleHi:'गुरुजी स्टूडेंट क्रेडिट कार्ड', description:'Education loan up to Rs 15 lakh for higher education at 4% interest.', descriptionHi:'उच्च शिक्षा के लिए 4% ब्याज पर ₹15 लाख तक लोन।', state:'Jharkhand', category:'education', eligibility:'Jharkhand students for higher education', eligibilityHi:'उच्च शिक्षा चाहने वाले झारखंड छात्र', benefits:'Rs 15 lakh loan at 4%', benefitsHi:'₹15 लाख लोन 4% पर', applicationUrl:'https://jharkhand.gov.in', requiredDocuments:['12th Marksheet','Admission Letter','Aadhaar Card'], isActive:true },
    { title:'Mukhyamantri Rozgar Srijan Yojana', titleHi:'मुख्यमंत्री रोजगार सृजन योजना', description:'Self-employment support with loan and subsidy for new businesses.', descriptionHi:'नए बिजनेस के लिए लोन और सब्सिडी सहायता।', state:'Jharkhand', category:'finance', eligibility:'Jharkhand youth aged 18-45', eligibilityHi:'18-45 वर्ष झारखंड युवा', benefits:'Loan + 40% subsidy', benefitsHi:'लोन + 40% सब्सिडी', applicationUrl:'https://msme.jharkhand.gov.in', requiredDocuments:['Aadhaar Card','Business Plan','Education Certificate'], isActive:true },
    { title:'Jharkhand Pension Scheme', titleHi:'झारखंड पेंशन योजना', description:'Monthly pension for old age, widow, and disabled persons.', descriptionHi:'वृद्ध, विधवा और दिव्यांग व्यक्तियों को मासिक पेंशन।', state:'Jharkhand', category:'other', eligibility:'Senior citizens/widows/disabled in Jharkhand', eligibilityHi:'झारखंड के बुजुर्ग/विधवा/दिव्यांग', benefits:'Rs 1000/month', benefitsHi:'₹1000/माह', applicationUrl:'https://ekalyan.jharkhand.gov.in', requiredDocuments:['Aadhaar Card','Age/Disability Proof','Bank Account'], isActive:true },
    { title:'Maiya Samman Yojana', titleHi:'मइया सम्मान योजना', description:'Rs 1000 monthly financial assistance to women in Jharkhand.', descriptionHi:'झारखंड की महिलाओं को ₹1000 मासिक आर्थिक सहायता।', state:'Jharkhand', category:'women', eligibility:'Women aged 18-50 in Jharkhand', eligibilityHi:'18-50 वर्ष झारखंड की महिलाएं', benefits:'Rs 1000/month', benefitsHi:'₹1000/माह', applicationUrl:'https://jharkhand.gov.in', requiredDocuments:['Aadhaar Card','Bank Account','Domicile'], isActive:true },
    { title:'Krishi Ashirwad Yojana', titleHi:'कृषि आशीर्वाद योजना', description:'Rs 5000 per acre per year for small and marginal farmers.', descriptionHi:'छोटे और सीमांत किसानों को ₹5000/एकड़/वर्ष।', state:'Jharkhand', category:'agriculture', eligibility:'Farmers with up to 5 acres in Jharkhand', eligibilityHi:'5 एकड़ तक भूमि वाले झारखंड किसान', benefits:'Rs 5000/acre/year', benefitsHi:'₹5000/एकड़/वर्ष', applicationUrl:'https://mmkay.jharkhand.gov.in', requiredDocuments:['Aadhaar Card','Land Records','Bank Account'], isActive:true },
  ];

  await Scheme.insertMany(schemes);
  console.log(`Seeded ${schemes.length} schemes successfully!`);
  process.exit(0);
}

seedSchemes().catch(err => { console.error(err); process.exit(1); });
