require('dotenv').config();
const mongoose = require('mongoose');
const Scheme = require('../models/Scheme');
const User = require('../models/User');

async function seedSchemes() {
  await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/gramseva');
  console.log('Connected to MongoDB');

  // Get admin user
  let admin = await User.findOne({ role: 'admin' });
  if (!admin) {
    admin = await User.create({ name: 'Admin', email: 'admin@gramseva.in', password: 'admin123', role: 'admin', state: 'Bihar', isVerified: true });
  }

  // Clear existing schemes
  await Scheme.deleteMany({});
  console.log('Cleared old schemes');

  const schemes = [
    // BIHAR (15)
    { title:'Bihar Student Credit Card Scheme', titleHi:'बिहार स्टूडेंट क्रेडिट कार्ड योजना', state:'Bihar', category:'education', description:'Education loan up to Rs 4 lakh for higher education students of Bihar.', descriptionHi:'बिहार के उच्च शिक्षा छात्रों के लिए 4 लाख रुपये तक का शिक्षा ऋण।', eligibility:'Bihar students for higher education', benefits:'Up to Rs 4 lakh loan', applicationUrl:'https://www.7nishchay-yuvaupmission.bihar.gov.in', isActive:true, createdBy:admin._id },
    { title:'Mukhyamantri Kanya Utthan Yojana', titleHi:'मुख्यमंत्री कन्या उत्थान योजना', state:'Bihar', category:'women', description:'Financial assistance for girl students from birth to graduation.', descriptionHi:'जन्म से स्नातक तक बालिकाओं को वित्तीय सहायता।', eligibility:'Girl students of Bihar', benefits:'Up to Rs 50000', applicationUrl:'https://edudbt.bih.nic.in', isActive:true, createdBy:admin._id },
    { title:'Bihar Civil Seva Protsahan Yojana', titleHi:'बिहार सिविल सेवा प्रोत्साहन योजना', state:'Bihar', category:'education', description:'Financial reward for BC/EBC students clearing UPSC/BPSC prelims.', descriptionHi:'UPSC/BPSC प्रारंभिक परीक्षा उत्तीर्ण करने वाले BC/EBC छात्रों को वित्तीय पुरस्कार।', eligibility:'BC/EBC students clearing UPSC/BPSC prelims', benefits:'Rs 50000-100000', applicationUrl:'https://fts.bih.nic.in', isActive:true, createdBy:admin._id },
    { title:'Kushal Yuva Program', titleHi:'कुशल युवा प्रोग्राम', state:'Bihar', category:'education', description:'Skill training program for Bihar youth aged 15-28 years.', descriptionHi:'15-28 वर्ष के बिहार युवाओं के लिए कौशल प्रशिक्षण कार्यक्रम।', eligibility:'Bihar youth skill training', benefits:'Free skill training + certificate', applicationUrl:'https://www.7nishchay-yuvaupmission.bihar.gov.in', isActive:true, createdBy:admin._id },
    { title:'Mukhyamantri Vridhjan Pension Yojana', titleHi:'मुख्यमंत्री वृद्धजन पेंशन योजना', state:'Bihar', category:'health', description:'Monthly pension for senior citizens of Bihar above 60 years.', descriptionHi:'60 वर्ष से अधिक आयु के बिहार के वरिष्ठ नागरिकों को मासिक पेंशन।', eligibility:'Senior citizens above 60', benefits:'Rs 400-500 per month', applicationUrl:'https://www.sspmis.bihar.gov.in', isActive:true, createdBy:admin._id },
    { title:'Mukhyamantri Nishchay Swayam Sahayata Bhatta', titleHi:'मुख्यमंत्री निश्चय स्वयं सहायता भत्ता', state:'Bihar', category:'finance', description:'Monthly allowance for unemployed youth while searching for jobs.', descriptionHi:'नौकरी खोजते समय बेरोजगार युवाओं को मासिक भत्ता।', eligibility:'Unemployed youth', benefits:'Rs 1000 per month for 2 years', applicationUrl:'https://www.7nishchay-yuvaupmission.bihar.gov.in', isActive:true, createdBy:admin._id },
    { title:'Bihar Diesel Anudan Yojana', titleHi:'बिहार डीजल अनुदान योजना', state:'Bihar', category:'agriculture', description:'Diesel subsidy for farmers for irrigation purposes.', descriptionHi:'सिंचाई के लिए किसानों को डीजल अनुदान।', eligibility:'Farmers', benefits:'Rs 50 per litre subsidy', applicationUrl:'https://dbtagriculture.bihar.gov.in', isActive:true, createdBy:admin._id },
    { title:'Bihar Beej Anudan Scheme', titleHi:'बिहार बीज अनुदान योजना', state:'Bihar', category:'agriculture', description:'Subsidy on seeds for farmers purchasing certified seeds.', descriptionHi:'प्रमाणित बीज खरीदने वाले किसानों को बीज पर अनुदान।', eligibility:'Farmers purchasing seeds', benefits:'50% subsidy on seeds', applicationUrl:'https://dbtagriculture.bihar.gov.in', isActive:true, createdBy:admin._id },
    { title:'Bihar Krishi Input Subsidy Scheme', titleHi:'बिहार कृषि इनपुट अनुदान योजना', state:'Bihar', category:'agriculture', description:'Subsidy for farmers affected by natural disasters.', descriptionHi:'प्राकृतिक आपदाओं से प्रभावित किसानों को अनुदान।', eligibility:'Farmers affected by disasters', benefits:'Up to Rs 13500 per hectare', applicationUrl:'https://dbtagriculture.bihar.gov.in', isActive:true, createdBy:admin._id },
    { title:'Mukhyamantri Kanya Vivah Yojana', titleHi:'मुख्यमंत्री कन्या विवाह योजना', state:'Bihar', category:'women', description:'Financial assistance for marriage of girls from economically weaker families.', descriptionHi:'आर्थिक रूप से कमजोर परिवारों की बेटियों की शादी के लिए वित्तीय सहायता।', eligibility:'Economically weaker families', benefits:'Rs 5000', applicationUrl:'https://serviceonline.bihar.gov.in', isActive:true, createdBy:admin._id },
    { title:'Bihar Labour Welfare Schemes', titleHi:'बिहार श्रमिक कल्याण योजनाएं', state:'Bihar', category:'finance', description:'Various welfare schemes for registered construction workers.', descriptionHi:'पंजीकृत निर्माण श्रमिकों के लिए विभिन्न कल्याण योजनाएं।', eligibility:'Registered workers', benefits:'Multiple benefits', applicationUrl:'https://bocw.bihar.gov.in', isActive:true, createdBy:admin._id },
    { title:'Mukhyamantri Udyami Yojana', titleHi:'मुख्यमंत्री उद्यमी योजना', state:'Bihar', category:'finance', description:'Loan and subsidy for SC/ST/women entrepreneurs to start business.', descriptionHi:'SC/ST/महिला उद्यमियों को व्यवसाय शुरू करने के लिए ऋण और अनुदान।', eligibility:'SC/ST/women entrepreneurs', benefits:'Up to Rs 10 lakh loan with 50% subsidy', applicationUrl:'https://udyami.bihar.gov.in', isActive:true, createdBy:admin._id },
    { title:'PMAY Bihar', titleHi:'प्रधानमंत्री आवास योजना बिहार', state:'Bihar', category:'housing', description:'Housing assistance for low-income households in Bihar.', descriptionHi:'बिहार में कम आय वाले परिवारों को आवास सहायता।', eligibility:'Low-income households', benefits:'Rs 1.2-1.5 lakh', applicationUrl:'https://pmaymis.gov.in', isActive:true, createdBy:admin._id },
    { title:'Bihar Scholarship Schemes', titleHi:'बिहार छात्रवृत्ति योजनाएं', state:'Bihar', category:'education', description:'Scholarships for reserved category students in Bihar.', descriptionHi:'बिहार में आरक्षित वर्ग के छात्रों के लिए छात्रवृत्ति।', eligibility:'Reserved category students', benefits:'Varies by category', applicationUrl:'https://scholarships.gov.in', isActive:true, createdBy:admin._id },
    { title:'Jal Jeevan Hariyali Abhiyan', titleHi:'जल जीवन हरियाली अभियान', state:'Bihar', category:'agriculture', description:'Water conservation and tree plantation scheme for farmers.', descriptionHi:'किसानों के लिए जल संरक्षण और वृक्षारोपण योजना।', eligibility:'Farmers and rural households', benefits:'Subsidy for water harvesting', applicationUrl:'https://jaljeevanhariyali.bihar.gov.in', isActive:true, createdBy:admin._id },
    // UTTAR PRADESH (15)
    { title:'Kanya Sumangala Yojana', titleHi:'कन्या सुमंगला योजना', state:'Uttar Pradesh', category:'women', description:'Financial assistance for girl child from birth to graduation.', descriptionHi:'जन्म से स्नातक तक बालिकाओं को वित्तीय सहायता।', eligibility:'Girl child families', benefits:'Rs 15000 in installments', applicationUrl:'https://mksy.up.gov.in', isActive:true, createdBy:admin._id },
    { title:'Mukhyamantri Samuhik Vivah Yojana', titleHi:'मुख्यमंत्री सामूहिक विवाह योजना', state:'Uttar Pradesh', category:'women', description:'Mass marriage scheme for economically weaker families.', descriptionHi:'आर्थिक रूप से कमजोर परिवारों के लिए सामूहिक विवाह योजना।', eligibility:'Economically weaker families', benefits:'Rs 51000 per couple', applicationUrl:'https://sspy-up.gov.in', isActive:true, createdBy:admin._id },
    { title:'UP Scholarship Scheme', titleHi:'यूपी छात्रवृत्ति योजना', state:'Uttar Pradesh', category:'education', description:'Scholarships for students from pre-matric to post-matric level.', descriptionHi:'प्री-मैट्रिक से पोस्ट-मैट्रिक स्तर तक छात्रों के लिए छात्रवृत्ति।', eligibility:'Students', benefits:'Tuition fee + maintenance', applicationUrl:'https://scholarship.up.gov.in', isActive:true, createdBy:admin._id },
    { title:'One District One Product (ODOP)', titleHi:'एक जिला एक उत्पाद', state:'Uttar Pradesh', category:'finance', description:'Support for MSMEs and artisans to promote district-specific products.', descriptionHi:'जिला-विशिष्ट उत्पादों को बढ़ावा देने के लिए MSME और कारीगरों को सहायता।', eligibility:'MSMEs/artisans', benefits:'Loan subsidy + marketing support', applicationUrl:'https://odopup.in', isActive:true, createdBy:admin._id },
    { title:'Mukhyamantri Yuva Swarozgar Yojana', titleHi:'मुख्यमंत्री युवा स्वरोजगार योजना', state:'Uttar Pradesh', category:'finance', description:'Loan for youth entrepreneurs to start their own business.', descriptionHi:'युवा उद्यमियों को अपना व्यवसाय शुरू करने के लिए ऋण।', eligibility:'Entrepreneurs aged 18-40', benefits:'Up to Rs 25 lakh loan', applicationUrl:'https://diupmsme.upsdc.gov.in', isActive:true, createdBy:admin._id },
    { title:'Berojgari Bhatta Yojana', titleHi:'बेरोजगारी भत्ता योजना', state:'Uttar Pradesh', category:'finance', description:'Monthly unemployment allowance for educated unemployed youth.', descriptionHi:'शिक्षित बेरोजगार युवाओं को मासिक बेरोजगारी भत्ता।', eligibility:'Unemployed youth', benefits:'Rs 1000-1500 per month', applicationUrl:'https://sewayojan.up.nic.in', isActive:true, createdBy:admin._id },
    { title:'PMAY UP', titleHi:'प्रधानमंत्री आवास योजना यूपी', state:'Uttar Pradesh', category:'housing', description:'Housing for all scheme for low-income households.', descriptionHi:'कम आय वाले परिवारों के लिए सबके लिए आवास योजना।', eligibility:'Low-income households', benefits:'Rs 1.2-2.5 lakh', applicationUrl:'https://pmaymis.gov.in', isActive:true, createdBy:admin._id },
    { title:'UP Free Laptop/Tablet Scheme', titleHi:'यूपी मुफ्त लैपटॉप/टैबलेट योजना', state:'Uttar Pradesh', category:'education', description:'Free tablets for eligible students who passed board exams.', descriptionHi:'बोर्ड परीक्षा उत्तीर्ण करने वाले पात्र छात्रों को मुफ्त टैबलेट।', eligibility:'Eligible students', benefits:'Free tablet', applicationUrl:'https://upcmo.up.nic.in', isActive:true, createdBy:admin._id },
    { title:'Mukhyamantri Krishak Durghatna Kalyan Yojana', titleHi:'मुख्यमंत्री कृषक दुर्घटना कल्याण योजना', state:'Uttar Pradesh', category:'agriculture', description:'Compensation for farmers in case of accident or death.', descriptionHi:'दुर्घटना या मृत्यु की स्थिति में किसानों को मुआवजा।', eligibility:'Farmers', benefits:'Up to Rs 5 lakh', applicationUrl:'https://balrampur.nic.in', isActive:true, createdBy:admin._id },
    { title:'UP Pension Scheme', titleHi:'यूपी पेंशन योजना', state:'Uttar Pradesh', category:'health', description:'Monthly pension for senior citizens, widows and disabled.', descriptionHi:'वरिष्ठ नागरिकों, विधवाओं और दिव्यांगों को मासिक पेंशन।', eligibility:'Senior citizens/widows/divyang', benefits:'Rs 500-1000 per month', applicationUrl:'https://sspy-up.gov.in', isActive:true, createdBy:admin._id },
    { title:'UP Ration Card Scheme', titleHi:'यूपी राशन कार्ड योजना', state:'Uttar Pradesh', category:'finance', description:'Subsidized food grains for BPL households.', descriptionHi:'BPL परिवारों को रियायती खाद्यान्न।', eligibility:'BPL households', benefits:'Subsidized ration', applicationUrl:'https://fcs.up.gov.in', isActive:true, createdBy:admin._id },
    { title:'Vishwakarma Shram Samman Yojana', titleHi:'विश्वकर्मा श्रम सम्मान योजना', state:'Uttar Pradesh', category:'finance', description:'Skill training and toolkit for traditional workers.', descriptionHi:'पारंपरिक कामगारों के लिए कौशल प्रशिक्षण और टूलकिट।', eligibility:'Traditional workers', benefits:'Free training + Rs 10000 toolkit', applicationUrl:'https://diupmsme.upsdc.gov.in', isActive:true, createdBy:admin._id },
    { title:'Abhyudaya Free Coaching Scheme', titleHi:'अभ्युदय मुफ्त कोचिंग योजना', state:'Uttar Pradesh', category:'education', description:'Free coaching for competitive exam aspirants by IAS/IPS officers.', descriptionHi:'IAS/IPS अधिकारियों द्वारा प्रतियोगी परीक्षा अभ्यर्थियों को मुफ्त कोचिंग।', eligibility:'Competitive exam aspirants', benefits:'Free coaching', applicationUrl:'https://abhyuday.up.gov.in', isActive:true, createdBy:admin._id },
    { title:'Nivesh Mitra Scheme', titleHi:'निवेश मित्र योजना', state:'Uttar Pradesh', category:'finance', description:'Single window clearance for businesses and startups.', descriptionHi:'व्यवसायों और स्टार्टअप के लिए सिंगल विंडो क्लीयरेंस।', eligibility:'Businesses/startups', benefits:'Fast-track approvals', applicationUrl:'https://niveshmitra.up.nic.in', isActive:true, createdBy:admin._id },
    { title:'UP Skill Development Mission', titleHi:'यूपी कौशल विकास मिशन', state:'Uttar Pradesh', category:'education', description:'Skill development training for youth employment.', descriptionHi:'युवा रोजगार के लिए कौशल विकास प्रशिक्षण।', eligibility:'Youth skill development', benefits:'Free training + placement', applicationUrl:'https://upsdm.gov.in', isActive:true, createdBy:admin._id },
    // PUNJAB (15)
    { title:'Punjab Old Age Pension Scheme', titleHi:'पंजाब वृद्धावस्था पेंशन योजना', state:'Punjab', category:'health', description:'Monthly pension for senior citizens of Punjab.', descriptionHi:'पंजाब के वरिष्ठ नागरिकों को मासिक पेंशन।', eligibility:'Senior citizens', benefits:'Rs 1500 per month', applicationUrl:'https://punjab.gov.in', isActive:true, createdBy:admin._id },
    { title:'Punjab Widow Pension Scheme', titleHi:'पंजाब विधवा पेंशन योजना', state:'Punjab', category:'women', description:'Monthly pension for widowed women.', descriptionHi:'विधवा महिलाओं को मासिक पेंशन।', eligibility:'Widowed women', benefits:'Rs 1500 per month', applicationUrl:'https://punjab.gov.in', isActive:true, createdBy:admin._id },
    { title:'Punjab Ashirwad Scheme', titleHi:'पंजाब आशीर्वाद योजना', state:'Punjab', category:'women', description:'Marriage support for SC/BPL girls.', descriptionHi:'SC/BPL लड़कियों की शादी के लिए सहायता।', eligibility:'SC/BPL girls marriage support', benefits:'Rs 21000', applicationUrl:'https://punjab.gov.in', isActive:true, createdBy:admin._id },
    { title:'Punjab Scholarship Schemes', titleHi:'पंजाब छात्रवृत्ति योजनाएं', state:'Punjab', category:'education', description:'Various scholarships for students of Punjab.', descriptionHi:'पंजाब के छात्रों के लिए विभिन्न छात्रवृत्तियां।', eligibility:'Students', benefits:'Tuition + maintenance', applicationUrl:'https://scholarships.gov.in', isActive:true, createdBy:admin._id },
    { title:'PMAY Punjab', titleHi:'प्रधानमंत्री आवास योजना पंजाब', state:'Punjab', category:'housing', description:'Housing for low-income households in Punjab.', descriptionHi:'पंजाब में कम आय वाले परिवारों के लिए आवास।', eligibility:'Low-income households', benefits:'Rs 1.2-2.5 lakh', applicationUrl:'https://pmaymis.gov.in', isActive:true, createdBy:admin._id },
    { title:'MGNREGA Punjab', titleHi:'मनरेगा पंजाब', state:'Punjab', category:'finance', description:'100 days guaranteed employment for rural households.', descriptionHi:'ग्रामीण परिवारों को 100 दिन की गारंटीकृत रोजगार।', eligibility:'Rural households', benefits:'100 days work', applicationUrl:'https://nrega.nic.in', isActive:true, createdBy:admin._id },
    { title:'Punjab Ghar Ghar Rozgar Scheme', titleHi:'पंजाब घर घर रोजगार योजना', state:'Punjab', category:'finance', description:'Employment generation for unemployed youth.', descriptionHi:'बेरोजगार युवाओं के लिए रोजगार सृजन।', eligibility:'Unemployed youth', benefits:'Job placement', applicationUrl:'https://www.pgrkam.com', isActive:true, createdBy:admin._id },
    { title:'Sehat Insurance Scheme', titleHi:'सेहत बीमा योजना', state:'Punjab', category:'health', description:'Health insurance for Punjab residents up to Rs 5 lakh.', descriptionHi:'पंजाब निवासियों के लिए 5 लाख रुपये तक का स्वास्थ्य बीमा।', eligibility:'Punjab residents', benefits:'Rs 5 lakh health cover', applicationUrl:'https://sha.punjab.gov.in', isActive:true, createdBy:admin._id },
    { title:'Punjab Labour Card Schemes', titleHi:'पंजाब लेबर कार्ड योजनाएं', state:'Punjab', category:'finance', description:'Welfare schemes for registered construction workers.', descriptionHi:'पंजीकृत निर्माण श्रमिकों के लिए कल्याण योजनाएं।', eligibility:'Registered workers', benefits:'Multiple benefits', applicationUrl:'https://pblabour.gov.in', isActive:true, createdBy:admin._id },
    { title:'Punjab State Rural Livelihood Mission', titleHi:'पंजाब राज्य ग्रामीण आजीविका मिशन', state:'Punjab', category:'finance', description:'Self-employment for rural women and youth through SHGs.', descriptionHi:'SHG के माध्यम से ग्रामीण महिलाओं और युवाओं के लिए स्वरोजगार।', eligibility:'Rural women/youth', benefits:'Loan + training', applicationUrl:'https://punjab.gov.in', isActive:true, createdBy:admin._id },
    { title:'Kisan Karz Rahat Scheme', titleHi:'किसान कर्ज राहत योजना', state:'Punjab', category:'agriculture', description:'Farm loan waiver scheme for small farmers.', descriptionHi:'छोटे किसानों के लिए कृषि ऋण माफी योजना।', eligibility:'Farmers', benefits:'Loan waiver', applicationUrl:'https://punjab.gov.in', isActive:true, createdBy:admin._id },
    { title:'Punjab Startup Scheme', titleHi:'पंजाब स्टार्टअप योजना', state:'Punjab', category:'finance', description:'Support for startups and entrepreneurs in Punjab.', descriptionHi:'पंजाब में स्टार्टअप और उद्यमियों के लिए सहायता।', eligibility:'Startups/entrepreneurs', benefits:'Funding + mentorship', applicationUrl:'https://startuppunjab.gov.in', isActive:true, createdBy:admin._id },
    { title:'Bhagwant Mann Health Scheme', titleHi:'भगवंत मान स्वास्थ्य योजना', state:'Punjab', category:'health', description:'Health insurance for families needing medical treatment.', descriptionHi:'चिकित्सा उपचार की आवश्यकता वाले परिवारों के लिए स्वास्थ्य बीमा।', eligibility:'Families needing health insurance', benefits:'Free treatment', applicationUrl:'https://sha.punjab.gov.in', isActive:true, createdBy:admin._id },
    { title:'Punjab Skill Development Mission', titleHi:'पंजाब कौशल विकास मिशन', state:'Punjab', category:'education', description:'Skill training for youth employment.', descriptionHi:'युवा रोजगार के लिए कौशल प्रशिक्षण।', eligibility:'Youth', benefits:'Free training', applicationUrl:'https://psdm.gov.in', isActive:true, createdBy:admin._id },
    { title:'Pensioner Sewa Portal', titleHi:'पेंशनर सेवा पोर्टल', state:'Punjab', category:'health', description:'Online portal for pensioner services.', descriptionHi:'पेंशनभोगी सेवाओं के लिए ऑनलाइन पोर्टल।', eligibility:'Pensioners', benefits:'Online pension services', applicationUrl:'https://punjab.gov.in', isActive:true, createdBy:admin._id },
    // HARYANA (15)
    { title:'Old Age Samman Allowance', titleHi:'वृद्धावस्था सम्मान भत्ता', state:'Haryana', category:'health', description:'Monthly pension for senior citizens of Haryana.', descriptionHi:'हरियाणा के वरिष्ठ नागरिकों को मासिक पेंशन।', eligibility:'Senior citizens', benefits:'Rs 2500 per month', applicationUrl:'https://pension.socialjusticehry.gov.in', isActive:true, createdBy:admin._id },
    { title:'Haryana Widow Pension Scheme', titleHi:'हरियाणा विधवा पेंशन योजना', state:'Haryana', category:'women', description:'Monthly pension for widowed women.', descriptionHi:'विधवा महिलाओं को मासिक पेंशन।', eligibility:'Widowed women', benefits:'Rs 2500 per month', applicationUrl:'https://pension.socialjusticehry.gov.in', isActive:true, createdBy:admin._id },
    { title:'Disability Pension Scheme', titleHi:'दिव्यांग पेंशन योजना', state:'Haryana', category:'health', description:'Monthly pension for disabled citizens.', descriptionHi:'दिव्यांग नागरिकों को मासिक पेंशन।', eligibility:'Divyang citizens', benefits:'Rs 2500 per month', applicationUrl:'https://pension.socialjusticehry.gov.in', isActive:true, createdBy:admin._id },
    { title:'Parivar Pehchan Patra (PPP)', titleHi:'परिवार पहचान पत्र', state:'Haryana', category:'finance', description:'Family ID for all Haryana families for scheme delivery.', descriptionHi:'योजना वितरण के लिए सभी हरियाणा परिवारों का पारिवारिक पहचान पत्र।', eligibility:'Haryana families', benefits:'Access to all schemes', applicationUrl:'https://meraparivar.haryana.gov.in', isActive:true, createdBy:admin._id },
    { title:'Haryana Saksham Yuva Yojana', titleHi:'हरियाणा सक्षम युवा योजना', state:'Haryana', category:'finance', description:'Unemployment allowance and honorarium for educated youth.', descriptionHi:'शिक्षित युवाओं को बेरोजगारी भत्ता और मानदेय।', eligibility:'Educated unemployed youth', benefits:'Rs 3000-9000 per month', applicationUrl:'https://hreyahs.gov.in', isActive:true, createdBy:admin._id },
    { title:'Mukhyamantri Vivah Shagun Yojana', titleHi:'मुख्यमंत्री विवाह शगुन योजना', state:'Haryana', category:'women', description:'Financial assistance for marriage of girls from weaker sections.', descriptionHi:'कमजोर वर्गों की बेटियों की शादी के लिए वित्तीय सहायता।', eligibility:'Economically weaker girls', benefits:'Rs 51000', applicationUrl:'https://haryanascbc.gov.in', isActive:true, createdBy:admin._id },
    { title:'Haryana Labour Welfare Schemes', titleHi:'हरियाणा श्रमिक कल्याण योजनाएं', state:'Haryana', category:'finance', description:'Welfare schemes for registered workers.', descriptionHi:'पंजीकृत श्रमिकों के लिए कल्याण योजनाएं।', eligibility:'Registered workers', benefits:'Multiple benefits', applicationUrl:'https://hrylabour.gov.in', isActive:true, createdBy:admin._id },
    { title:'PMAY Haryana', titleHi:'प्रधानमंत्री आवास योजना हरियाणा', state:'Haryana', category:'housing', description:'Housing for low-income households.', descriptionHi:'कम आय वाले परिवारों के लिए आवास।', eligibility:'Low-income households', benefits:'Rs 1.2-2.5 lakh', applicationUrl:'https://pmaymis.gov.in', isActive:true, createdBy:admin._id },
    { title:'Haryana Scholarship Schemes', titleHi:'हरियाणा छात्रवृत्ति योजनाएं', state:'Haryana', category:'education', description:'Scholarships for students of Haryana.', descriptionHi:'हरियाणा के छात्रों के लिए छात्रवृत्ति।', eligibility:'Students', benefits:'Tuition + maintenance', applicationUrl:'https://scholarships.gov.in', isActive:true, createdBy:admin._id },
    { title:'Meri Fasal Mera Byora', titleHi:'मेरी फसल मेरा ब्यौरा', state:'Haryana', category:'agriculture', description:'Crop registration for MSP procurement and insurance.', descriptionHi:'MSP खरीद और बीमा के लिए फसल पंजीकरण।', eligibility:'Farmers', benefits:'MSP guarantee + insurance', applicationUrl:'https://fasal.haryana.gov.in', isActive:true, createdBy:admin._id },
    { title:'Haryana Kaushal Rozgar Nigam', titleHi:'हरियाणा कौशल रोजगार निगम', state:'Haryana', category:'finance', description:'Contractual employment through transparent recruitment.', descriptionHi:'पारदर्शी भर्ती के माध्यम से संविदा रोजगार।', eligibility:'Job seekers', benefits:'Government jobs', applicationUrl:'https://hkrnl.itiharyana.gov.in', isActive:true, createdBy:admin._id },
    { title:'Ladli Social Security Scheme', titleHi:'लाडली सामाजिक सुरक्षा योजना', state:'Haryana', category:'women', description:'Financial security for girl child.', descriptionHi:'बालिकाओं के लिए वित्तीय सुरक्षा।', eligibility:'Girl child', benefits:'Rs 5000 per year', applicationUrl:'https://wcdhry.gov.in', isActive:true, createdBy:admin._id },
    { title:'Deen Dayal Jan Awas Yojana', titleHi:'दीन दयाल जन आवास योजना', state:'Haryana', category:'housing', description:'Affordable housing for all.', descriptionHi:'सभी के लिए किफायती आवास।', eligibility:'Affordable housing seekers', benefits:'Subsidized housing', applicationUrl:'https://hfrp.haryana.gov.in', isActive:true, createdBy:admin._id },
    { title:'Haryana Skill Development Mission', titleHi:'हरियाणा कौशल विकास मिशन', state:'Haryana', category:'education', description:'Skill training for youth.', descriptionHi:'युवाओं के लिए कौशल प्रशिक्षण।', eligibility:'Youth skill development', benefits:'Free training + placement', applicationUrl:'https://hsdm.org.in', isActive:true, createdBy:admin._id },
    { title:'Chirayu Ayushman Haryana', titleHi:'चिरायु आयुष्मान हरियाणा', state:'Haryana', category:'health', description:'Health insurance up to Rs 5 lakh for eligible families.', descriptionHi:'पात्र परिवारों के लिए 5 लाख रुपये तक का स्वास्थ्य बीमा।', eligibility:'Health beneficiaries', benefits:'Rs 5 lakh health cover', applicationUrl:'https://nha.gov.in', isActive:true, createdBy:admin._id },
    // JHARKHAND (15)
    { title:'Guruji Student Credit Card Scheme', titleHi:'गुरुजी स्टूडेंट क्रेडिट कार्ड योजना', state:'Jharkhand', category:'education', description:'Education loan for students for higher education.', descriptionHi:'उच्च शिक्षा के लिए छात्रों को शिक्षा ऋण।', eligibility:'Students for higher education', benefits:'Up to Rs 10 lakh loan', applicationUrl:'https://jharkhand.gov.in', isActive:true, createdBy:admin._id },
    { title:'Mukhyamantri Rozgar Srijan Yojana', titleHi:'मुख्यमंत्री रोजगार सृजन योजना', state:'Jharkhand', category:'finance', description:'Loan and subsidy for entrepreneurs.', descriptionHi:'उद्यमियों के लिए ऋण और अनुदान।', eligibility:'Entrepreneurs', benefits:'Up to Rs 25 lakh', applicationUrl:'https://jharkhand.gov.in', isActive:true, createdBy:admin._id },
    { title:'Savitribai Phule Kishori Samriddhi Yojana', titleHi:'सावित्रीबाई फुले किशोरी समृद्धि योजना', state:'Jharkhand', category:'women', description:'Financial assistance for school-going girls.', descriptionHi:'स्कूल जाने वाली लड़कियों को वित्तीय सहायता।', eligibility:'School-going girls', benefits:'Rs 2500-20000 in installments', applicationUrl:'https://jharkhand.gov.in', isActive:true, createdBy:admin._id },
    { title:'Sarvjan Pension Yojana', titleHi:'सर्वजन पेंशन योजना', state:'Jharkhand', category:'health', description:'Pension for senior citizens, widows and disabled.', descriptionHi:'वरिष्ठ नागरिकों, विधवाओं और दिव्यांगों को पेंशन।', eligibility:'Senior citizens/widows/divyang', benefits:'Rs 1000 per month', applicationUrl:'https://jharsewa.jharkhand.gov.in', isActive:true, createdBy:admin._id },
    { title:'Phulo Jhano Ashirwad Yojana', titleHi:'फूलो झानो आशीर्वाद योजना', state:'Jharkhand', category:'women', description:'Self-employment support for women groups.', descriptionHi:'महिला समूहों के लिए स्वरोजगार सहायता।', eligibility:'Women self-employment groups', benefits:'Loan + training', applicationUrl:'https://jharkhand.gov.in', isActive:true, createdBy:admin._id },
    { title:'Jharkhand Krishi Rin Mafi Yojana', titleHi:'झारखंड कृषि ऋण माफी योजना', state:'Jharkhand', category:'agriculture', description:'Farm loan waiver for small farmers.', descriptionHi:'छोटे किसानों के लिए कृषि ऋण माफी।', eligibility:'Farmers', benefits:'Loan waiver up to Rs 50000', applicationUrl:'https://jharkhand.gov.in', isActive:true, createdBy:admin._id },
    { title:'Birsa Harit Gram Yojana', titleHi:'बिरसा हरित ग्राम योजना', state:'Jharkhand', category:'agriculture', description:'Tree plantation and green village development.', descriptionHi:'वृक्षारोपण और हरित ग्राम विकास।', eligibility:'Rural households/farmers', benefits:'Free saplings + income', applicationUrl:'https://jharkhand.gov.in', isActive:true, createdBy:admin._id },
    { title:'Jharkhand CM Employment Generation Scheme', titleHi:'झारखंड मुख्यमंत्री रोजगार सृजन योजना', state:'Jharkhand', category:'finance', description:'Employment generation for unemployed youth.', descriptionHi:'बेरोजगार युवाओं के लिए रोजगार सृजन।', eligibility:'Unemployed youth', benefits:'Loan + subsidy', applicationUrl:'https://jharkhand.gov.in', isActive:true, createdBy:admin._id },
    { title:'Jharkhand Scholarship Schemes', titleHi:'झारखंड छात्रवृत्ति योजनाएं', state:'Jharkhand', category:'education', description:'Scholarships for students of Jharkhand.', descriptionHi:'झारखंड के छात्रों के लिए छात्रवृत्ति।', eligibility:'Students', benefits:'Tuition + maintenance', applicationUrl:'https://ekalyan.cgg.gov.in', isActive:true, createdBy:admin._id },
    { title:'Abua Awas Yojana', titleHi:'अबुआ आवास योजना', state:'Jharkhand', category:'housing', description:'Housing for homeless families in Jharkhand.', descriptionHi:'झारखंड में बेघर परिवारों के लिए आवास।', eligibility:'Homeless families', benefits:'Free pucca house', applicationUrl:'https://jharkhand.gov.in', isActive:true, createdBy:admin._id },
    { title:'Savitribai Jyotiba Phule Pension Scheme', titleHi:'सावित्रीबाई ज्योतिबा फुले पेंशन योजना', state:'Jharkhand', category:'health', description:'Pension for women and senior citizens.', descriptionHi:'महिलाओं और वरिष्ठ नागरिकों के लिए पेंशन।', eligibility:'Women/senior citizens', benefits:'Rs 1000 per month', applicationUrl:'https://jharsewa.jharkhand.gov.in', isActive:true, createdBy:admin._id },
    { title:'Jharkhand Labour Welfare Schemes', titleHi:'झारखंड श्रमिक कल्याण योजनाएं', state:'Jharkhand', category:'finance', description:'Welfare for registered workers.', descriptionHi:'पंजीकृत श्रमिकों के लिए कल्याण।', eligibility:'Registered workers', benefits:'Multiple benefits', applicationUrl:'https://jharkhand.gov.in', isActive:true, createdBy:admin._id },
    { title:'PMAY Jharkhand', titleHi:'प्रधानमंत्री आवास योजना झारखंड', state:'Jharkhand', category:'housing', description:'Housing for low-income households.', descriptionHi:'कम आय वाले परिवारों के लिए आवास।', eligibility:'Low-income households', benefits:'Rs 1.2-1.5 lakh', applicationUrl:'https://pmaymis.gov.in', isActive:true, createdBy:admin._id },
    { title:'Jharkhand Skill Development Mission', titleHi:'झारखंड कौशल विकास मिशन', state:'Jharkhand', category:'education', description:'Skill training for youth.', descriptionHi:'युवाओं के लिए कौशल प्रशिक्षण।', eligibility:'Youth skill development', benefits:'Free training + placement', applicationUrl:'https://jharkhand.gov.in', isActive:true, createdBy:admin._id },
    { title:'Aapki Yojana Aapki Sarkar', titleHi:'आपकी योजना आपकी सरकार', state:'Jharkhand', category:'finance', description:'General citizen welfare services portal.', descriptionHi:'सामान्य नागरिक कल्याण सेवा पोर्टल।', eligibility:'General citizen welfare services', benefits:'Access to all schemes', applicationUrl:'https://jharkhand.gov.in', isActive:true, createdBy:admin._id },
  ];

  await Scheme.insertMany(schemes);
  console.log(`Inserted ${schemes.length} schemes successfully!`);
  process.exit(0);
}

seedSchemes().catch(e => { console.error(e); process.exit(1); });
